# Generated by Django 3.2 on 2021-05-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='PlaceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='images')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=500)),
                ('requestdate', models.DateTimeField(auto_now=True)),
                ('tourname', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='TourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('startdateofjourney', models.CharField(max_length=30)),
                ('enddateofjourney', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('travelon', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('traveltype', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tours',
            },
        ),
        migrations.CreateModel(
            name='WayPointsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourid', models.CharField(max_length=500)),
                ('lat', models.DateTimeField(auto_now=True)),
                ('long', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'waypoints',
            },
        ),
    ]
