# Generated by Django 3.2 on 2021-05-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypointsmodel',
            name='lat',
            field=models.CharField(max_length=60),
        ),
    ]
