# Generated by Django 3.2 on 2021-05-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0002_alter_waypointsmodel_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypointsmodel',
            name='placeid',
            field=models.CharField(default='', max_length=500),
        ),
    ]
